use crate::{
    bitset::BitSet,
    cell_configs::CELL_CONFIGS,
    mesh::Mesh,
    plane::Plane,
    qef,
    vertex_index::{neg_offset, offset, Index, VarIndex, VertexIndex, EDGES_ON_FACE},
    AsUSize, ImplicitFunction, RealField,
};
use bbox::BoundingBox;
use nalgebra as na;
use num_traits::Float;
use rayon::prelude::*;
use std::{
    cell::{Cell, RefCell},
    cmp,
    collections::{BTreeSet, HashMap},
    error, fmt,
};

// How accurately find zero crossings.
const PRECISION: f32 = 0.05;

//  Edge indexes
//
//      +-------9-------+
//     /|              /|
//    7 |            10 |              ^
//   /  8            /  11            /
//  +-------6-------+   |     ^    higher indexes in y
//  |   |           |   |     |     /
//  |   +-------3---|---+     |    /
//  2  /            5  /  higher indexes
//  | 1             | 4      in z
//  |/              |/        |/
//  o-------0-------+         +-- higher indexes in x ---->
//
// Point o is the reference point of the current cell.
// All edges go from lower indexes to higher indexes.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Edge {
    A = 0,
    B = 1,
    C = 2,
    D = 3,
    E = 4,
    F = 5,
    G = 6,
    H = 7,
    I = 8,
    J = 9,
    K = 10,
    L = 11,
}

impl Edge {
    pub fn from_usize(e: usize) -> Edge {
        match e {
            0 => Edge::A,
            1 => Edge::B,
            2 => Edge::C,
            3 => Edge::D,
            4 => Edge::E,
            5 => Edge::F,
            6 => Edge::G,
            7 => Edge::H,
            8 => Edge::I,
            9 => Edge::J,
            10 => Edge::K,
            11 => Edge::L,
            _ => panic!("Not edge for {:?}", e),
        }
    }
    pub fn base(self) -> Edge {
        Edge::from_usize(self as usize % 3)
    }
}

// Cell offsets of edges
const EDGE_OFFSET: [Index; 12] = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 1, 0],
    [1, 0, 0],
    [1, 0, 0],
    [0, 0, 1],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 0],
];

// Quad definition for edges 0-2.
const QUADS: [[Edge; 4]; 3] = [
    [Edge::A, Edge::G, Edge::J, Edge::D],
    [Edge::B, Edge::E, Edge::K, Edge::H],
    [Edge::C, Edge::I, Edge::L, Edge::F],
];

use std::sync::LazyLock;
static OUTSIDE_EDGES_PER_CORNER: LazyLock<[BitSet; 8]> = LazyLock::new(|| {
    [
        BitSet::from_3bits(0, 1, 2),
        BitSet::from_3bits(0, 4, 5),
        BitSet::from_3bits(1, 3, 8),
        BitSet::from_3bits(3, 4, 11),
        BitSet::from_3bits(2, 6, 7),
        BitSet::from_3bits(5, 6, 10),
        BitSet::from_3bits(7, 8, 9),
        BitSet::from_3bits(9, 10, 11),
    ]
});

#[derive(Debug)]
pub enum DualContouringError {
    HitZero(String),
}

impl error::Error for DualContouringError {}

impl fmt::Display for DualContouringError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            DualContouringError::HitZero(ref s) => write!(f, "Hit zero value for {}", s),
        }
    }
}

// A vertex of the mesh. This can be either a primary vertex of the sampled mesh or a vertex
// generated by joining multiple vertices in the octree.
#[derive(Debug)]
pub struct Vertex<S: RealField> {
    index: Index,
    qef: RefCell<qef::Qef<S>>,
    neighbors: [Vec<VarIndex>; 6],
    parent: Cell<Option<usize>>,
    children: Vec<usize>,
    // Index of this vertex in the final mesh.
    mesh_index: Cell<Option<usize>>,
    edge_intersections: [u32; 12],
    euler_characteristic: i32,
}

impl<S: RealField> Clone for Vertex<S> {
    fn clone(&self) -> Vertex<S> {
        Vertex {
            index: self.index,
            qef: self.qef.clone(),
            neighbors: [
                self.neighbors[0].clone(),
                self.neighbors[1].clone(),
                self.neighbors[2].clone(),
                self.neighbors[3].clone(),
                self.neighbors[4].clone(),
                self.neighbors[5].clone(),
            ],
            parent: self.parent.clone(),
            children: self.children.clone(),
            mesh_index: self.mesh_index.clone(),
            edge_intersections: self.edge_intersections,
            euler_characteristic: self.euler_characteristic,
        }
    }
}

impl<S: RealField> Vertex<S> {
    fn is_2manifold(&self) -> bool {
        if self.euler_characteristic != 1 {
            return false;
        }
        for edges_on_face in EDGES_ON_FACE.iter() {
            let mut sum = 0;
            for edge in *edges_on_face {
                sum += self.edge_intersections[edge];
            }
            if sum != 0 && sum != 2 {
                return false;
            }
        }
        true
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct EdgeIndex {
    edge: Edge,
    index: Index,
}

impl EdgeIndex {
    pub fn base(&self) -> EdgeIndex {
        EdgeIndex {
            edge: self.edge.base(),
            index: offset(self.index, EDGE_OFFSET[self.edge as usize]),
        }
    }
}

/// Struct containing all the intermediary state for the different stages of tessellation.
#[derive(Clone)]
pub struct ManifoldDualContouring<'a, S: RealField> {
    function: &'a dyn ImplicitFunction<S>,
    origin: na::Point3<S>,
    dim: [usize; 3],
    mesh: RefCell<Mesh<S>>,
    res: S,
    error: S,
    value_grid: HashMap<Index, S>,
    edge_grid: RefCell<HashMap<EdgeIndex, Plane<S>>>,
    // The Vertex Octtree. vertex_octtree[0] stores the leaf vertices. vertex_octtree[1] the next
    // layer and so on. vertex_octtree.len() is the depth of the octtree.
    vertex_octtree: Vec<Vec<Vertex<S>>>,
    // Map from VertexIndex to vertex_octtree[0]
    vertex_index_map: HashMap<VertexIndex, usize>,
}

// Returns the next largest power of 2
fn pow2roundup(x: usize) -> usize {
    let mut x = x;
    x -= 1;
    x |= x >> 1;
    x |= x >> 2;
    x |= x >> 4;
    x |= x >> 8;
    x |= x >> 16;
    x |= x >> 32;
    x + 1
}

// Returns a BitSet containing all egdes connected to "edge" in this cell.
fn get_connected_edges(edge: Edge, cell: BitSet) -> BitSet {
    for &edge_set in CELL_CONFIGS[cell.as_u32() as usize].iter() {
        if edge_set.get(edge as usize) {
            return edge_set;
        }
    }
    panic!("Did not find edge_set for {:?} and {:?}", edge, cell);
}

// Returns all BitSets containing egdes connected to one of edge_set in this cell.
fn get_connected_edges_from_edge_set(edge_set: BitSet, cell: BitSet) -> Vec<BitSet> {
    let mut result = Vec::new();
    for &cell_edge_set in CELL_CONFIGS[cell.as_u32() as usize].iter() {
        if !cell_edge_set.intersect(edge_set).empty() {
            result.push(cell_edge_set);
        }
    }
    debug_assert!(
        result
            .iter()
            .fold(BitSet::zero(), |sum, x| sum.merge(*x))
            .intersect(edge_set)
            == edge_set,
        "result: {:?} does not contain all edges from egde_set: {:?}",
        result,
        edge_set
    );
    result
}

fn half_index(input: &Index) -> Index {
    [input[0] / 2, input[1] / 2, input[2] / 2]
}

// Will add the following vertices to neighbors:
// All vertices in the same octtree subcell as start and connected to start.
fn add_connected_vertices_in_subcell<S: RealField>(
    base: &[Vertex<S>],
    start: &Vertex<S>,
    neigbors: &mut BTreeSet<usize>,
) {
    let parent_index = half_index(&start.index);
    for neighbor_index_vector in &start.neighbors {
        for neighbor_index in neighbor_index_vector.iter() {
            match *neighbor_index {
                VarIndex::Index(vi) => {
                    let neighbor = &base[vi];
                    if half_index(&neighbor.index) == parent_index && neigbors.insert(vi) {
                        add_connected_vertices_in_subcell(base, &base[vi], neigbors);
                    }
                }
                VarIndex::VertexIndex(vi) => {
                    panic!("unexpected VertexIndex {:?}", vi);
                }
            }
        }
    }
}

fn add_child_to_parent<S: RealField + Float + From<f32>>(
    child: &Vertex<S>,
    parent: &mut Vertex<S>,
) {
    parent.qef.borrow_mut().merge(&*child.qef.borrow());
    for dim in 0..3 {
        let relevant_neighbor = dim * 2 + (child.index[dim] & 1);
        for neighbor in &child.neighbors[relevant_neighbor] {
            if !parent.neighbors[relevant_neighbor].contains(neighbor) {
                parent.neighbors[relevant_neighbor].push(*neighbor);
            }
        }
    }
}

fn subsample_euler_characteristics<S: RealField>(
    children: &BTreeSet<usize>,
    vertices: &[Vertex<S>],
) -> ([u32; 12], i32) {
    let mut intersections = [0u32; 12];
    let mut euler = 0i32;
    let mut inner_sum = 0;
    for vertex in children.iter().map(|i| &vertices[*i]) {
        let i = vertex.index;
        let corner_index = (i[2] & 1) << 2 | (i[1] & 1) << 1 | (i[0] & 1);
        let outside_edges = OUTSIDE_EDGES_PER_CORNER[corner_index];
        for (i, vertex_edge_intersection) in vertex.edge_intersections.iter().enumerate().take(12) {
            if outside_edges.get(i) {
                intersections[i] += vertex_edge_intersection;
            } else {
                inner_sum += vertex_edge_intersection;
            }
        }
        euler += vertex.euler_characteristic;
    }
    debug_assert_eq!(
        inner_sum % 4,
        0,
        "inner_sum {} is not divisible by 4.",
        inner_sum
    );
    euler -= inner_sum as i32 / 4;
    (intersections, euler)
}

fn subsample_octtree<S: RealField + Float + From<f32>>(base: &[Vertex<S>]) -> Vec<Vertex<S>> {
    let mut result = Vec::new();
    for (i, vertex) in base.iter().enumerate() {
        if vertex.parent.get().is_none() {
            let mut neighbor_set = BTreeSet::new();
            neighbor_set.insert(i);
            add_connected_vertices_in_subcell(base, vertex, &mut neighbor_set);
            let (intersections, euler) = subsample_euler_characteristics(&neighbor_set, base);
            let mut parent = Vertex {
                index: half_index(&vertex.index),
                qef: RefCell::new(qef::Qef::new(&[], BoundingBox::neg_infinity())),
                neighbors: [
                    Vec::new(),
                    Vec::new(),
                    Vec::new(),
                    Vec::new(),
                    Vec::new(),
                    Vec::new(),
                ],
                parent: Cell::new(None),
                children: Vec::new(),
                mesh_index: Cell::new(None),
                edge_intersections: intersections,
                euler_characteristic: euler,
            };
            for &neighbor_index in &neighbor_set {
                let child = &base[neighbor_index];
                debug_assert!(
                    child.parent.get().is_none(),
                    "child #{:?} already has parent #{:?}",
                    neighbor_index,
                    child.parent.get().unwrap()
                );
                debug_assert!(!parent.children.contains(&neighbor_index));
                parent.children.push(neighbor_index);
                add_child_to_parent(child, &mut parent);
                child.parent.set(Some(result.len()));
            }
            result.push(parent);
        }
    }
    for vertex in &mut result {
        for neighbor_vec in &mut vertex.neighbors {
            for neighbor in neighbor_vec.iter_mut() {
                match *neighbor {
                    VarIndex::VertexIndex(_) => panic!("unexpected VertexIndex in normal node."),
                    VarIndex::Index(i) => {
                        *neighbor = VarIndex::Index(base[i].parent.get().unwrap())
                    }
                }
            }
        }
    }
    result
}

// ---------------------------------------------------------------------------
// Bounding-box discovery
// ---------------------------------------------------------------------------

// Follow the implicit function's gradient downhill from a perturbed origin to find
// a point that is inside (f < 0) or at the nearest surface point, then step inside.
// The slight initial perturbation avoids degenerate normals at exact symmetry axes
// (e.g. a torus lying in the xz-plane has an undefined normal at the origin).
fn find_hint<S: Float + RealField + From<f32>>(
    f: &dyn ImplicitFunction<S>,
    res: S,
) -> na::Point3<S> {
    let zero: S = From::from(0f32);
    let eps: S = From::from(0.001f32);
    let mut p = na::Point3::new(eps, eps, eps);
    for _ in 0..1000 {
        let v = f.value(&p);
        if v < zero {
            return p;
        }
        let n = f.normal(&p);
        let p_new = p - n * v;
        let step = (p_new - p).norm();
        if !step.is_finite() || step < res {
            break;
        }
        p = p_new;
    }
    // p is at (or near) the nearest surface point from outside; step inward by res.
    p - f.normal(&p) * res
}

// Sphere-march from `start` along `dir` until the sign of f changes.
// Returns the first point past the zero crossing, or None if max distance exceeded.
// Precondition: f.value(start) < 0  (start is inside the object).
// find_hint guarantees this, which also means init_sign = -1 and the march correctly
// detects the exit from the object.  If f(start) == 0 the march still terminates
// but each step returns immediately, giving a near-hint AABB that verify_and_expand
// will then expand to the true surface extents.
fn march_axis<S: Float + RealField + From<f32>>(
    f: &dyn ImplicitFunction<S>,
    start: na::Point3<S>,
    dir: na::Vector3<S>,
    res: S,
) -> Option<na::Point3<S>> {
    let max_dist: S = From::from(1000.0f32);
    let mut p = start;
    let mut v = f.value(&p);
    let init_sign = Float::signum(v);
    for _ in 0..100_000 {
        let step = Float::max(Float::abs(v), res);
        p += dir * step;
        if (p - start).norm() > max_dist {
            return None;
        }
        v = f.value(&p);
        if Float::signum(v) != init_sign {
            return Some(p);
        }
    }
    None
}

// Returns true when the three circles (centre = vertex, radius = SDF value) share a
// common intersection point, which proves the zero surface cannot cross the triangle.
// All three vertices are assumed co-planar.
fn circles_have_triple_intersection<S: Float + RealField + From<f32>>(
    a: na::Point3<S>,
    ra: S,
    b: na::Point3<S>,
    rb: S,
    c: na::Point3<S>,
    rc: S,
) -> bool {
    let zero: S = From::from(0f32);
    let d = (b - a).norm();
    if d <= zero {
        return true; // degenerate: A == B
    }
    // Circles A and B must overlap.
    if ra + rb < d {
        return false;
    }
    // 2-D coordinates in the plane of A, B, C: A at origin, B along +x.
    let e1 = (b - a) / d;
    let ca = c - a;
    let cx = e1.dot(&ca);
    let cy = (ca - e1 * cx).norm();

    // x-coordinate of the intersection points of circles A and B.
    let x = (d * d + ra * ra - rb * rb) / (d + d);
    let y_sq = ra * ra - x * x;
    if y_sq < zero {
        return false;
    }
    let y = Float::sqrt(y_sq);

    // Check both intersection points against circle C = (cx, cy, rc).
    let dx = x - cx;
    let in_c = |py: S| dx * dx + (py - cy) * (py - cy) <= rc * rc;
    in_c(y) || in_c(-y)
}

// Checks whether the zero surface can exit through triangle A-B-C.
// Returns None if the triangle is safe, or Some(d) where d is the distance the
// containing face must be shifted outward to clear the surface.
#[allow(clippy::too_many_arguments)]
fn check_triangle<S: Float + RealField + From<f32>>(
    f: &dyn ImplicitFunction<S>,
    res: S,
    a: na::Point3<S>,
    va: S,
    b: na::Point3<S>,
    vb: S,
    c: na::Point3<S>,
    vc: S,
) -> Option<S> {
    let zero: S = From::from(0f32);
    // Any corner inside the object requires the face to expand.
    if va <= zero {
        return Some(Float::abs(va));
    }
    if vb <= zero {
        return Some(Float::abs(vb));
    }
    if vc <= zero {
        return Some(Float::abs(vc));
    }
    // Base case: triangle at (or below) grid resolution — assume safe.
    let ab = (b - a).norm();
    let bc = (c - b).norm();
    let ca = (a - c).norm();
    let longest = Float::max(Float::max(ab, bc), ca);
    if longest < res {
        return None;
    }
    // Termination via triple-circle test.
    if circles_have_triple_intersection(a, va, b, vb, c, vc) {
        return None;
    }
    // Bisect the longest edge; the two halves each have longest edge ≤ original/2,
    // which guarantees convergence to `res` in O(log(longest/res)) levels.
    let two: S = From::from(2f32);
    let (p0, vp0, p1, vp1, opp, vopp) = if ab >= bc && ab >= ca {
        (a, va, b, vb, c, vc)
    } else if bc >= ca {
        (b, vb, c, vc, a, va)
    } else {
        (c, vc, a, va, b, vb)
    };
    let mid = na::Point3::new(
        (p0.x + p1.x) / two,
        (p0.y + p1.y) / two,
        (p0.z + p1.z) / two,
    );
    let vmid = f.value(&mid);
    if vmid <= zero {
        return Some(Float::abs(vmid));
    }
    check_triangle(f, res, p0, vp0, mid, vmid, opp, vopp)
        .or_else(|| check_triangle(f, res, mid, vmid, p1, vp1, opp, vopp))
}

// Returns the four corners of an axis-aligned face of `bbox`.
// axis: 0 = X, 1 = Y, 2 = Z; is_max: false = min face, true = max face.
fn face_corners<S: Float + RealField + From<f32>>(
    bbox: &BoundingBox<S, 3>,
    axis: usize,
    is_max: bool,
) -> [na::Point3<S>; 4] {
    let a1 = (axis + 1) % 3;
    let a2 = (axis + 2) % 3;
    let fixed = if is_max { bbox.max[axis] } else { bbox.min[axis] };
    let zero: S = From::from(0f32);
    let mk = |v1: S, v2: S| -> na::Point3<S> {
        let mut p = na::Point3::new(zero, zero, zero);
        p[axis] = fixed;
        p[a1] = v1;
        p[a2] = v2;
        p
    };
    [
        mk(bbox.min[a1], bbox.min[a2]),
        mk(bbox.max[a1], bbox.min[a2]),
        mk(bbox.min[a1], bbox.max[a2]),
        mk(bbox.max[a1], bbox.max[a2]),
    ]
}

// Verify all six faces of `bbox` and expand each face outward until the zero surface
// does not exit through it.
//
// Each expansion shifts the face by at least `res`, so the loop terminates in at most
// O(surface_extent / res) iterations per face.  The limit of 10_000 is a defensive
// safety-cap for degenerate functions that somehow evade the SDF guarantee.
fn verify_and_expand<S: Float + RealField + From<f32>>(
    f: &dyn ImplicitFunction<S>,
    res: S,
    bbox: &mut BoundingBox<S, 3>,
) {
    for axis in 0..3usize {
        for &is_max in &[false, true] {
            for _ in 0..10_000 {
                let corners = face_corners(bbox, axis, is_max);
                let v = [
                    f.value(&corners[0]),
                    f.value(&corners[1]),
                    f.value(&corners[2]),
                    f.value(&corners[3]),
                ];
                // The quad is split into two triangles.
                let unsafe_dist =
                    check_triangle(f, res, corners[0], v[0], corners[1], v[1], corners[2], v[2])
                        .or_else(|| {
                            check_triangle(
                                f, res, corners[1], v[1], corners[3], v[3], corners[2], v[2],
                            )
                        });
                match unsafe_dist {
                    None => break,
                    Some(d) => {
                        if is_max {
                            bbox.max[axis] += d + res;
                        } else {
                            bbox.min[axis] -= d + res;
                        }
                    }
                }
            }
        }
    }
}

// Discover an axis-aligned bounding box for the zero surface of `f` by
// sphere-marching outward from an interior hint point, then verifying and
// expanding each face until the surface is fully enclosed.
fn find_bounds<S: Float + RealField + From<f32>>(
    f: &dyn ImplicitFunction<S>,
    res: S,
) -> BoundingBox<S, 3> {
    let hint = find_hint(f, res);

    let zero: S = From::from(0f32);
    let one: S = From::from(1f32);
    let dirs: [na::Vector3<S>; 6] = [
        na::Vector3::new(one, zero, zero),
        na::Vector3::new(-one, zero, zero),
        na::Vector3::new(zero, one, zero),
        na::Vector3::new(zero, -one, zero),
        na::Vector3::new(zero, zero, one),
        na::Vector3::new(zero, zero, -one),
    ];

    let mut surface_points: Vec<na::Point3<S>> = Vec::new();
    for dir in dirs {
        if let Some(p) = march_axis(f, hint, dir, res) {
            surface_points.push(p);
        }
    }

    assert!(
        !surface_points.is_empty(),
        "tessellation: could not find any surface near the origin"
    );

    let min_pt = na::Point3::new(
        surface_points
            .iter()
            .map(|p| p.x)
            .fold(surface_points[0].x, |a, b| Float::min(a, b)),
        surface_points
            .iter()
            .map(|p| p.y)
            .fold(surface_points[0].y, |a, b| Float::min(a, b)),
        surface_points
            .iter()
            .map(|p| p.z)
            .fold(surface_points[0].z, |a, b| Float::min(a, b)),
    );
    let max_pt = na::Point3::new(
        surface_points
            .iter()
            .map(|p| p.x)
            .fold(surface_points[0].x, |a, b| Float::max(a, b)),
        surface_points
            .iter()
            .map(|p| p.y)
            .fold(surface_points[0].y, |a, b| Float::max(a, b)),
        surface_points
            .iter()
            .map(|p| p.z)
            .fold(surface_points[0].z, |a, b| Float::max(a, b)),
    );

    let pad = na::Vector3::new(res, res, res);
    let mut bbox = BoundingBox::new(&(min_pt - pad), &(max_pt + pad));
    verify_and_expand(f, res, &mut bbox);
    bbox
}

/// Progress event emitted by [`ManifoldDualContouring::tessellate_with_progress`].
#[derive(Clone, Debug)]
#[allow(missing_docs)] // field names (done, total, layer, face_count) are self-documenting
pub enum ProgressEvent {
    /// Bounding box found; the sampling grid will now be built.
    BoundsFound,
    /// Sampling the value grid. `done` leaf cells inserted so far; `total` is the grid
    /// volume (an overestimate — actual insertions are typically 5–15 % of this).
    SamplingGrid    { done: usize, total: usize },
    /// Compacting the value grid by removing cells with no sign-change neighbours.
    CompactingGrid  { done: usize, total: usize },
    /// Finding zero-crossings on grid edges.
    GeneratingEdges { done: usize, total: usize },
    /// Building leaf vertices from edge crossings.
    GeneratingVerts { done: usize, total: usize },
    /// One octree coarsening pass completed (`layer` = 0 is the leaf level).
    OctreeLayer     { layer: usize },
    /// Solving QEF systems for mesh vertices.
    SolvingQef      { done: usize, total: usize },
    /// Generating mesh quads from edge crossings.
    GeneratingQuad  { done: usize, total: usize },
    /// Tessellation complete; `face_count` triangles produced.
    Done            { face_count: usize },
}

impl ProgressEvent {
    /// Returns a scalar in `[0, 1]` estimating overall progress.
    pub fn progress_fraction(&self) -> f32 {
        fn interp(start: f32, end: f32, done: usize, total: usize) -> f32 {
            let t = if total == 0 { 1.0 } else { (done as f32 / total as f32).min(1.0) };
            start + (end - start) * t
        }
        match self {
            Self::BoundsFound                        => 0.05,
            Self::SamplingGrid    { done, total }    => interp(0.05, 0.55, *done, *total),
            Self::CompactingGrid  { done, total }    => interp(0.55, 0.62, *done, *total),
            Self::GeneratingEdges { done, total }    => interp(0.62, 0.67, *done, *total),
            Self::GeneratingVerts { done, total }    => interp(0.67, 0.72, *done, *total),
            Self::OctreeLayer     { layer }          =>
                0.72 + 0.03 * (1.0 - 0.5_f32.powi(*layer as i32)),
            Self::SolvingQef      { done, total }    => interp(0.75, 0.90, *done, *total),
            Self::GeneratingQuad  { done, total }    => interp(0.90, 0.97, *done, *total),
            Self::Done            { .. }             => 1.0,
        }
    }
}

impl<'a, S: From<f32> + RealField + Float + AsUSize> ManifoldDualContouring<'a, S> {
    /// Constructor
    /// f: function to tessellate
    /// res: resolution
    /// relative_error: acceptable error threshold when simplifying the mesh.
    pub fn new(
        f: &'a dyn ImplicitFunction<S>,
        res: S,
        relative_error: S,
    ) -> ManifoldDualContouring<'a, S> {
        ManifoldDualContouring {
            function: f,
            origin: na::Point3::origin(),
            dim: [0, 0, 0],
            mesh: RefCell::new(Mesh {
                vertices: Vec::new(),
                faces: Vec::new(),
            }),
            res,
            error: res * relative_error,
            value_grid: HashMap::new(),
            edge_grid: RefCell::new(HashMap::new()),
            vertex_octtree: Vec::new(),
            vertex_index_map: HashMap::new(),
        }
    }
    /// Tessellate the given function.
    pub fn tessellate(&mut self) -> Option<Mesh<S>> {
        self.tessellate_with_progress(|_| {})
    }

    /// Tessellate, calling `progress` after each pipeline stage with a [`ProgressEvent`].
    /// The callback is called from the same thread and may update UI or send messages.
    pub fn tessellate_with_progress(&mut self, mut progress: impl FnMut(ProgressEvent)) -> Option<Mesh<S>> {
        let one: S = From::from(1f32);
        let mut bbox = find_bounds(self.function, self.res);
        bbox.dilate(one + self.res * From::from(1.1f32));
        self.origin = bbox.min;
        self.dim = std::array::from_fn(|i| Float::ceil(bbox.dim()[i] / self.res).as_usize());
        progress(ProgressEvent::BoundsFound);
        loop {
            match self.try_tessellate(&mut progress) {
                Ok(mesh) => return Some(mesh),
                // Tessellation failed because a grid cell value was exactly zero.
                // Retry with random padding and hope for the best.
                Err(_) => {
                    let padding = na::Vector3::new(
                        -self.res / From::from(10. + rand::random::<f32>().abs()),
                        -self.res / From::from(10. + rand::random::<f32>().abs()),
                        -self.res / From::from(10. + rand::random::<f32>().abs()),
                    );
                    self.origin += padding;
                    self.value_grid.clear();
                    self.mesh.borrow_mut().vertices.clear();
                    self.mesh.borrow_mut().faces.clear();
                    self.vertex_octtree.clear();
                    self.vertex_index_map.clear();
                }
            }
        }
    }

    fn tessellation_step1(&mut self, progress: &mut impl FnMut(ProgressEvent)) -> Option<DualContouringError> {
        let maxdim = cmp::max(self.dim[0], cmp::max(self.dim[1], self.dim[2]));
        let origin = self.origin;
        let origin_value = self.function.value(&origin);
        let total = self.dim[0] * self.dim[1] * self.dim[2];
        let mut done = 0usize;
        self.sample_value_grid([0, 0, 0], origin, pow2roundup(maxdim), origin_value, &mut done, total, progress)
    }

    // This method does the main work of tessellation.
    // It may fail, if the value in one of the grid cells yields exactly zero.
    fn try_tessellate(&mut self, progress: &mut impl FnMut(ProgressEvent)) -> Result<Mesh<S>, DualContouringError> {
        if let Some(e) = self.tessellation_step1(progress) {
            return Err(e);
        }

        let compact_total = self.value_grid.len();
        progress(ProgressEvent::CompactingGrid { done: 0, total: compact_total });
        self.compact_value_grid();
        progress(ProgressEvent::CompactingGrid { done: compact_total, total: compact_total });

        self.generate_edge_grid(progress);

        let (leafs, index_map) = self.generate_leaf_vertices(progress);
        self.vertex_index_map = index_map;
        self.vertex_octtree.push(leafs);

        let mut layer = 0usize;
        loop {
            progress(ProgressEvent::OctreeLayer { layer });
            let next = subsample_octtree(self.vertex_octtree.last().unwrap());
            if next.len() == self.vertex_octtree.last().unwrap().len() {
                break;
            }
            self.vertex_octtree.push(next);
            layer += 1;
        }

        self.solve_qefs(progress);

        let total_quads = self.edge_grid.borrow().len();
        for (i, &edge_index) in self.edge_grid.borrow().keys().enumerate() {
            progress(ProgressEvent::GeneratingQuad { done: i + 1, total: total_quads });
            self.compute_quad(edge_index);
        }

        let face_count = self.mesh.borrow().faces.len();
        progress(ProgressEvent::Done { face_count });

        Ok(self.mesh.borrow().clone())
    }

    #[allow(clippy::too_many_arguments)]
    fn sample_value_grid(
        &mut self,
        idx: Index,
        pos: na::Point3<S>,
        size: usize,
        val: S,
        done: &mut usize,
        total: usize,
        progress: &mut impl FnMut(ProgressEvent),
    ) -> Option<DualContouringError> {
        debug_assert!(size > 1);
        let mut midx = idx;
        let size = size / 2;
        let size_s: S = From::from(size as f32);
        let vpos = [
            pos,
            pos + na::Vector3::new(self.res, self.res, self.res) * size_s,
        ];
        let sub_cube_diagonal = size_s * self.res * Float::sqrt(From::from(3f32));

        for z in 0..2 {
            for y in 0..2 {
                for x in 0..2 {
                    let mpos = na::Point3::new(vpos[x].x, vpos[y].y, vpos[z].z);
                    let value = if midx == idx {
                        val
                    } else {
                        self.function.value(&mpos)
                    };

                    if value == From::from(0f32) {
                        return Some(DualContouringError::HitZero(format!("{}", mpos)));
                    }

                    if size > 1 && Float::abs(value) <= sub_cube_diagonal {
                        if let Some(e) = self.sample_value_grid(midx, mpos, size, value, done, total, progress) {
                            return Some(e);
                        }
                    } else {
                        self.value_grid.insert(midx, value);
                        *done += 1;
                        progress(ProgressEvent::SamplingGrid { done: *done, total });
                    }
                    midx[0] += size;
                }
                midx[0] -= 2 * size;
                midx[1] += size;
            }
            midx[1] -= 2 * size;
            midx[2] += size;
        }
        None
    }

    // Delete all values from value grid that do not have a value of opposing signum in any
    // neighboring index.
    // This might reduces memory usage by ~10x.
    fn compact_value_grid(&mut self) {
        // Collect all indexes to remove.
        let value_grid = &mut self.value_grid;
        let keys_to_remove: Vec<_> = value_grid
            .par_iter()
            .filter(|&(idx, &v)| {
                if idx[0] == 0 || idx[1] == 0 || idx[2] == 0 {
                    // This grid cell does not have neighbors in some directions. Ignore.
                    return false;
                }
                for z in 0..3 {
                    for y in 0..3 {
                        for x in 0..3 {
                            let adjacent_idx = [idx[0] + x - 1, idx[1] + y - 1, idx[2] + z - 1];
                            if let Some(&adjacent_value) = value_grid.get(&adjacent_idx)
                                && Float::signum(v) != Float::signum(adjacent_value)
                            {
                                // Don't collect indexes with opposing signum.
                                return false;
                            }
                        }
                    }
                }
                true
            })
            .map(|(k, _)| *k)
            .collect();
        for k in keys_to_remove {
            value_grid.remove(&k);
        }
        value_grid.shrink_to_fit();
    }

    // Store crossing positions of edges in edge_grid
    fn generate_edge_grid(&mut self, progress: &mut impl FnMut(ProgressEvent)) {
        let total = self.value_grid.len();
        let mut edge_grid = self.edge_grid.borrow_mut();
        for (done, (&point_idx, &point_value)) in self.value_grid.iter().enumerate() {
            progress(ProgressEvent::GeneratingEdges { done: done + 1, total });
            for &edge in &[Edge::A, Edge::B, Edge::C] {
                let mut adjacent_idx = point_idx;
                adjacent_idx[edge as usize] += 1;
                if let Some(&adjacent_value) = self.value_grid.get(&adjacent_idx) {
                    let point_pos = self.origin
                        + na::Vector3::new(
                            From::from(point_idx[0] as f32),
                            From::from(point_idx[1] as f32),
                            From::from(point_idx[2] as f32),
                        ) * self.res;
                    let mut adjacent_pos = point_pos;
                    adjacent_pos[edge as usize] += self.res;
                    if let Some(plane) =
                        self.find_zero(point_pos, point_value, adjacent_pos, adjacent_value)
                    {
                        edge_grid.insert(
                            EdgeIndex {
                                edge,
                                index: point_idx,
                            },
                            plane,
                        );
                    }
                }
            }
        }
    }

    // Solves QEFs in vertex stack, starting at the highest level, down all layers until the qef
    // error is below threshold.
    fn solve_qefs(&self, progress: &mut impl FnMut(ProgressEvent)) {
        if let Some(top_layer) = self.vertex_octtree.last() {
            let total = top_layer.len();
            for i in 0..total {
                progress(ProgressEvent::SolvingQef { done: i + 1, total });
                self.recursively_solve_qefs(&self.vertex_octtree.len() - 1, i);
            }
        }
    }

    fn recursively_solve_qefs(&self, layer: usize, index_in_layer: usize) -> usize {
        let vertex = &self.vertex_octtree[layer][index_in_layer];
        assert!(vertex.children.is_empty() || layer > 0);
        let error;
        {
            // Solve qef and store error.
            let mut qef = vertex.qef.borrow_mut();
            // Make sure we never solve a qef twice.
            debug_assert!(
                qef.error.is_nan(),
                "found solved qef layer {:?} index {:?} {:?} parent: {:?}",
                layer,
                index_in_layer,
                vertex.index,
                vertex.parent
            );
            qef.solve();
            error = qef.error;
        }
        let mut num_solved = 1;
        // If error exceed threshold, recurse into subvertices.
        if Float::abs(error) > self.error {
            for &child_index in &vertex.children {
                num_solved += self.recursively_solve_qefs(layer - 1, child_index);
            }
        }
        num_solved
    }

    // Generates leaf vertices along with a map that points VertexIndices to the index in the leaf
    // vertex vec.
    fn generate_leaf_vertices(&self, progress: &mut impl FnMut(ProgressEvent)) -> (Vec<Vertex<S>>, HashMap<VertexIndex, usize>) {
        let mut index_map = HashMap::new();
        let mut vertices = Vec::new();
        let edge_keys: Vec<EdgeIndex> = self.edge_grid.borrow().keys().copied().collect();
        let total = edge_keys.len();
        for (i, edge_index) in edge_keys.iter().enumerate() {
            progress(ProgressEvent::GeneratingVerts { done: i + 1, total });
            self.add_vertices_for_minimal_egde(edge_index, &mut vertices, &mut index_map);
        }
        for vertex in &mut vertices {
            for neighbor_vec in &mut vertex.neighbors {
                for neighbor in neighbor_vec.iter_mut() {
                    match *neighbor {
                        VarIndex::VertexIndex(vi) => *neighbor = VarIndex::Index(index_map[&vi]),
                        VarIndex::Index(_) => panic!("unexpected Index in fresh leaf map."),
                    }
                }
            }
        }
        for vi in 0..vertices.len() {
            for np in 0..vertices[vi].neighbors.len() {
                for ni in 0..vertices[vi].neighbors[np].len() {
                    match vertices[vi].neighbors[np][ni] {
                        VarIndex::VertexIndex(_) => panic!("unexpected VertexIndex."),
                        VarIndex::Index(i) => {
                            debug_assert!(
                                vertices[i].neighbors[np ^ 1].contains(&VarIndex::Index(vi)),
                                "vertex[{}].neighbors[{}][{}]=={:?},
                                 but vertex[{}].neighbors[{}]=={:?}\n{:?} vs. {:?}",
                                vi,
                                np,
                                ni,
                                vertices[vi].neighbors[np][ni],
                                i,
                                np ^ 1,
                                vertices[i].neighbors[np ^ 1],
                                vertices[vi],
                                vertices[i]
                            );
                        }
                    }
                }
            }
        }
        (vertices, index_map)
    }
    fn add_vertices_for_minimal_egde(
        &self,
        edge_index: &EdgeIndex,
        vertices: &mut Vec<Vertex<S>>,
        index_map: &mut HashMap<VertexIndex, usize>,
    ) {
        debug_assert!((edge_index.edge as usize) < 4);
        let cell_size = na::Vector3::new(self.res, self.res, self.res);
        for &quad_egde in &QUADS[edge_index.edge as usize] {
            let idx = neg_offset(edge_index.index, EDGE_OFFSET[quad_egde as usize]);

            let edge_set = get_connected_edges(quad_egde, self.bitset_for_cell(idx));
            let vertex_index = VertexIndex {
                edges: edge_set,
                index: idx,
            };
            index_map.entry(vertex_index).or_insert_with(|| {
                let mut neighbors = [
                    Vec::new(),
                    Vec::new(),
                    Vec::new(),
                    Vec::new(),
                    Vec::new(),
                    Vec::new(),
                ];
                for (i, neighbor) in neighbors.iter_mut().enumerate().take(6) {
                    if let Some(mut neighbor_index) = vertex_index.neighbor(i) {
                        for edges in get_connected_edges_from_edge_set(
                            neighbor_index.edges,
                            self.bitset_for_cell(neighbor_index.index),
                        ) {
                            neighbor_index.edges = edges;
                            let idx = VarIndex::VertexIndex(neighbor_index);
                            if !neighbor.contains(&idx) {
                                neighbor.push(idx);
                            }
                        }
                    }
                }
                let mut intersections = [0u32; 12];
                for edge in edge_set {
                    intersections[edge] = 1;
                }
                let tangent_planes: Vec<_> = edge_set
                    .map(|edge| {
                        self.get_edge_tangent_plane(&EdgeIndex {
                            edge: Edge::from_usize(edge),
                            index: idx,
                        })
                    })
                    .collect();
                let cell_origin = self.origin
                    + na::Vector3::new(
                        From::from(idx[0] as f32),
                        From::from(idx[1] as f32),
                        From::from(idx[2] as f32),
                    ) * self.res;
                vertices.push(Vertex {
                    index: idx,
                    qef: RefCell::new(qef::Qef::new(
                        &tangent_planes,
                        BoundingBox::new(&cell_origin, &(cell_origin + cell_size)),
                    )),
                    neighbors,
                    parent: Cell::new(None),
                    children: Vec::new(),
                    mesh_index: Cell::new(None),
                    edge_intersections: intersections,
                    euler_characteristic: 1,
                });
                vertices.len() - 1
            });
        }
    }

    fn get_edge_tangent_plane(&self, edge_index: &EdgeIndex) -> Plane<S> {
        if let Some(plane) = self.edge_grid.borrow().get(&edge_index.base()) {
            return *plane;
        }
        panic!(
            "could not find edge_point: {:?} -> {:?}",
            edge_index,
            edge_index.base()
        );
    }

    // Return the Point index (in self.mesh.vertices) the the point belonging to edge/idx.
    fn lookup_cell_point(&self, edge: Edge, idx: Index) -> usize {
        // Generate the proper vertex Index from a single edge and an Index.
        let edge_set = get_connected_edges(edge, self.bitset_for_cell(idx));
        let vertex_index = VertexIndex {
            edges: edge_set,
            index: idx,
        };

        // Convert the vertex index to index and layer in the Octtree.
        let mut octtree_index = self.vertex_index_map[&vertex_index];
        let mut octtree_layer = 0;
        // Walk up the chain of parents
        loop {
            let next_index = self.vertex_octtree[octtree_layer][octtree_index]
                .parent
                .get()
                .unwrap();
            let next_vertex = &self.vertex_octtree[octtree_layer + 1][next_index];
            let error = next_vertex.qef.borrow().error;
            if (!error.is_nan() && error > (self.error))
                || (octtree_layer == self.vertex_octtree.len() - 2)
                || !next_vertex.is_2manifold()
            {
                // Stop, if either the error is too large or we will reach the top.
                break;
            }
            octtree_layer += 1;
            octtree_index = next_index;
        }
        let vertex = &self.vertex_octtree[octtree_layer][octtree_index];
        // If the vertex exists in mesh, return its index.
        if let Some(mesh_index) = vertex.mesh_index.get() {
            return mesh_index;
        }
        // If not, store it in mesh and return its index.
        if vertex.qef.borrow().error.is_nan() {
            // Maybe the qef was not solved, since the error in the layer above was below the
            // threshold. But it seems, manifold criterion has catched and we need to solve it now.
            vertex.qef.borrow_mut().solve()
        }
        let qef_solution = vertex.qef.borrow().solution;
        let vertex_list = &mut self.mesh.borrow_mut().vertices;
        let result = vertex_list.len();
        vertex.mesh_index.set(Some(result));
        vertex_list.push([qef_solution.x, qef_solution.y, qef_solution.z]);
        result
    }

    fn bitset_for_cell(&self, idx: Index) -> BitSet {
        let mut idx = idx;
        let mut result = BitSet::zero();
        for z in 0..2 {
            for y in 0..2 {
                for x in 0..2 {
                    if let Some(&v) = self.value_grid.get(&idx) {
                        if v < From::from(0f32) {
                            result.set(z << 2 | y << 1 | x);
                        }
                    } else {
                        panic!("did not find value_grid[{:?}]", idx);
                    }
                    idx[0] += 1;
                }
                idx[0] -= 2;
                idx[1] += 1;
            }
            idx[1] -= 2;
            idx[2] += 1;
        }
        result
    }

    // Compute a quad for the given edge and append it to the list.
    fn compute_quad(&self, edge_index: EdgeIndex) {
        debug_assert!((edge_index.edge as usize) < 4);
        debug_assert!(edge_index.index.iter().all(|&i| i > 0));

        let mut p = Vec::with_capacity(4);
        for &quad_egde in &QUADS[edge_index.edge as usize] {
            let point_index = self.lookup_cell_point(
                quad_egde,
                neg_offset(edge_index.index, EDGE_OFFSET[quad_egde as usize]),
            );
            // Dedup points before insertion (two minimal vertices might end up in the same parent
            // vertex).
            if !p.contains(&point_index) {
                p.push(point_index)
            }
        }
        // Only try to generate meshes, if there are more then two points.
        if p.len() < 3 {
            return;
        }
        // Reverse order, if the edge is reversed.
        if let Some(&v) = self.value_grid.get(&edge_index.index)
            && v < From::from(0f32)
        {
            p.reverse();
        }
        let face_list = &mut self.mesh.borrow_mut().faces;
        // TODO: Fix this to choose the proper split.
        face_list.push([p[0], p[1], p[2]]);
        if p.len() == 4 {
            face_list.push([p[2], p[3], p[0]]);
        }
    }

    // If a is inside the object and b outside - this method returns the point on the line between
    // a and b where the object edge is. It also returns the normal on that point.
    // av and bv represent the object values at a and b.
    fn find_zero(&self, a: na::Point3<S>, av: S, b: na::Point3<S>, bv: S) -> Option<Plane<S>> {
        assert!(a != b);
        if Float::signum(av) == Float::signum(bv) {
            return None;
        }

        let d = b - a; // edge vector; all movement stays on this line
        let d_norm = d.norm();
        let prec: S = From::from(PRECISION);
        let precision = prec * self.res;
        let zero: S = From::from(0f32);
        let one: S = From::from(1f32);
        let half: S = From::from(0.5f32);
        let eps: S = From::from(1e-3f32);

        // Bracket invariant: lo_v <= 0 <= hi_v throughout.
        let (mut lo, mut lo_v, mut hi, mut hi_v) =
            if av <= zero { (a, av, b, bv) } else { (b, bv, a, av) };

        // Each bisection step halves the bracket. Adjacent grid corners are
        // distance res apart, so log2(1/PRECISION) ≈ 5 bisections suffice.
        // 64 is a generous safety cap that should never be reached in practice.
        for _ in 0..64 {
            // Work from the bracket endpoint closer to zero.
            let (p, pv) = if Float::abs(lo_v) <= Float::abs(hi_v) {
                (lo, lo_v)
            } else {
                (hi, hi_v)
            };

            if Float::abs(pv) < precision || (hi - lo).norm() < precision {
                return Some(Plane { p, n: self.function.normal(&p) });
            }

            // Newton step along the edge: p_new = p - f(p)/(normal(p)·d) * d.
            // Fall back to bisection if the projected gradient is too small
            // (surface nearly tangent to edge) or if Newton escapes the bracket.
            let grad = self.function.normal(&p).dot(&d);
            let bracket = hi - lo;
            let mid = lo + bracket * half;
            let p_new = if Float::abs(grad) > eps * d_norm {
                let candidate = p + d * (-pv / grad);
                let t = (candidate - lo).dot(&bracket) / bracket.norm_squared();
                if t > zero && t < one { candidate } else { mid }
            } else {
                mid
            };

            let new_v = self.function.value(&p_new);

            // Update bracket, maintaining lo_v <= 0 <= hi_v.
            if new_v <= zero {
                lo = p_new;
                lo_v = new_v;
            } else {
                hi = p_new;
                hi_v = new_v;
            }
            debug_assert!(
                lo_v <= zero && hi_v >= zero,
                "find_zero: bracket invariant violated: lo_v={lo_v:?} hi_v={hi_v:?}"
            );
        }

        // Max iterations reached; return the closer endpoint.
        let p = if Float::abs(lo_v) <= Float::abs(hi_v) { lo } else { hi };
        Some(Plane { p, n: self.function.normal(&p) })
    }
}

#[cfg(test)]
mod tests {
    use super::get_connected_edges_from_edge_set;
    use crate::bitset::BitSet;
    use crate::ImplicitFunction;
    use nalgebra as na;
    //  Corner indexes
    //
    //      6---------------7
    //     /|              /|
    //    / |             / |
    //   /  |            /  |
    //  4---------------5   |
    //  |   |           |   |
    //  |   2-----------|---3
    //  |  /            |  /
    //  | /             | /
    //  |/              |/
    //  0---------------1

    //  Edge indexes
    //
    //      +-------9-------+
    //     /|              /|
    //    7 |            10 |              ^
    //   /  8            /  11            /
    //  +-------6-------+   |     ^    higher indexes in y
    //  |   |           |   |     |     /
    //  |   +-------3---|---+     |    /
    //  2  /            5  /  higher indexes
    //  | 1             | 4      in z
    //  |/              |/        |/
    //  o-------0-------+         +-- higher indexes in x ---->

    #[test]
    fn connected_edges() {
        let cell = BitSet::from_4bits(0, 6, 3, 5);
        let edge_set = BitSet::from_4bits(4, 5, 10, 11);
        let connected_edges = get_connected_edges_from_edge_set(edge_set, cell);
        assert_eq!(connected_edges.len(), 2);
        assert!(connected_edges.contains(&BitSet::from_4bits(5, 5, 6, 10)));
        assert!(connected_edges.contains(&BitSet::from_4bits(3, 3, 4, 11)));
    }

    // ---------------------------------------------------------------------------
    // Test shapes
    // ---------------------------------------------------------------------------

    /// Sphere SDF centred at `center` with the given `radius`.
    struct Sphere {
        center: na::Point3<f64>,
        radius: f64,
    }
    impl Sphere {
        fn new(center: na::Point3<f64>, radius: f64) -> Self {
            Sphere { center, radius }
        }
    }
    impl super::ImplicitFunction<f64> for Sphere {
        fn value(&self, p: &na::Point3<f64>) -> f64 {
            (p - self.center).norm() - self.radius
        }
        fn normal(&self, p: &na::Point3<f64>) -> na::Vector3<f64> {
            (p - self.center).normalize()
        }
    }

    /// Torus SDF lying in the xz-plane with major radius `major` and tube
    /// radius `minor`.
    struct Torus {
        major: f64,
        minor: f64,
    }
    impl Torus {
        fn new(major: f64, minor: f64) -> Self {
            Torus { major, minor }
        }
    }
    impl super::ImplicitFunction<f64> for Torus {
        fn value(&self, p: &na::Point3<f64>) -> f64 {
            let q = (p.x * p.x + p.z * p.z).sqrt();
            ((q - self.major).powi(2) + p.y * p.y).sqrt() - self.minor
        }
        fn normal(&self, p: &na::Point3<f64>) -> na::Vector3<f64> {
            let q = (p.x * p.x + p.z * p.z).sqrt();
            let d = ((q - self.major).powi(2) + p.y * p.y).sqrt();
            na::Vector3::new(
                (q - self.major) * p.x / (q * d),
                p.y / d,
                (q - self.major) * p.z / (q * d),
            )
        }
    }

    // ---------------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------------

    /// Tessellate `f` at the given resolution (no simplification) and assert:
    /// - the mesh is closed (no boundary edges), and
    /// - every vertex lies within `res` of the zero surface.
    fn tessellate_and_check(
        f: &impl super::ImplicitFunction<f64>,
        res: f64,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let mut mdc = super::ManifoldDualContouring::new(f, res, 0.0);
        let mesh = mdc.tessellate().unwrap();
        mesh.is_closed()?;
        for v in &mesh.vertices {
            let p = na::Point3::new(v[0], v[1], v[2]);
            assert!(
                f.value(&p).abs() < res,
                "vertex {v:?} is {:.4} from the surface (tolerance {res})",
                f.value(&p).abs(),
            );
        }
        Ok(())
    }

    // ---------------------------------------------------------------------------
    // Tests
    // ---------------------------------------------------------------------------

    #[test]
    fn sphere_at_origin() -> Result<(), Box<dyn std::error::Error>> {
        // Baseline: origin is inside the object.
        tessellate_and_check(&Sphere::new(na::Point3::origin(), 1.0), 0.2)
    }

    #[test]
    fn sphere_off_centre() -> Result<(), Box<dyn std::error::Error>> {
        // Origin is well outside the object — exercises the bbox-discovery path.
        tessellate_and_check(&Sphere::new(na::Point3::new(5.0, 3.0, -2.0), 1.0), 0.2)
    }

    #[test]
    fn torus() -> Result<(), Box<dyn std::error::Error>> {
        // Non-convex surface; the hole through the middle stresses boundary
        // verification since the surface exits a naïve bbox in multiple places.
        tessellate_and_check(&Torus::new(1.0, 0.3), 0.15)
    }

    #[test]
    #[ignore]
    // This test exposes https://github.com/hmeyer/tessellation/issues/7
    fn sphere_with_simplification() -> Result<(), Box<dyn std::error::Error>> {
        let sphere = Sphere::new(na::Point3::origin(), 1.0);
        let mut mdc = super::ManifoldDualContouring::new(&sphere, 0.2, 0.1);
        let mesh = mdc.tessellate().unwrap();
        Ok(mesh.is_closed()?)
    }

    // -------------------------------------------------------------------------
    // Unit tests for bounding-box discovery helpers
    // -------------------------------------------------------------------------

    #[test]
    fn find_hint_inside_returns_at_once() {
        // Origin (+eps perturbation) is inside the unit sphere — no Newton steps needed.
        let sphere = Sphere::new(na::Point3::origin(), 1.0);
        let hint = super::find_hint(&sphere as &dyn super::ImplicitFunction<f64>, 0.2);
        assert!(
            sphere.value(&hint) < 0.0,
            "hint {hint:?} should be inside the unit sphere (f={:.4})",
            sphere.value(&hint),
        );
    }

    #[test]
    fn find_hint_outside_converges_inside() {
        // Origin is well outside; gradient descent must drive us inside the sphere.
        let sphere = Sphere::new(na::Point3::new(5.0, 3.0, -2.0), 1.0);
        let hint = super::find_hint(&sphere as &dyn super::ImplicitFunction<f64>, 0.2);
        assert!(
            sphere.value(&hint) < 0.0,
            "hint {hint:?} should be inside the offset sphere (f={:.4})",
            sphere.value(&hint),
        );
    }

    #[test]
    fn find_hint_torus_avoids_degenerate_origin() {
        // Origin lies on the torus's axis of symmetry where the normal is undefined.
        // The eps-perturbation in find_hint must side-step this singularity.
        let torus = Torus::new(1.0, 0.3);
        let hint = super::find_hint(&torus as &dyn super::ImplicitFunction<f64>, 0.15);
        assert!(
            torus.value(&hint) < 0.0,
            "hint {hint:?} should be inside the torus (f={:.4})",
            torus.value(&hint),
        );
    }

    #[test]
    fn circles_triple_intersection_safe() {
        // Equilateral triangle with side 1; radii 0.7.
        // ra+rb = 1.4 > d = 1, so circles A and B overlap.
        // Intersection points at x=0.5, y≈±0.49. C = (0.5, √3/2 ≈ 0.866).
        // Distance from (0.5, 0.49) to C ≈ 0.376 < 0.7 → inside circle C → safe.
        let a = na::Point3::new(0.0_f64, 0.0, 0.0);
        let b = na::Point3::new(1.0, 0.0, 0.0);
        let c = na::Point3::new(0.5, 3.0_f64.sqrt() / 2.0, 0.0);
        assert!(super::circles_have_triple_intersection(a, 0.7, b, 0.7, c, 0.7));
    }

    #[test]
    fn circles_triple_intersection_ab_no_overlap() {
        // Same triangle but radii too small: ra+rb = 0.6 < d = 1, so circles A and B
        // do not intersect at all → no triple intersection.
        let a = na::Point3::new(0.0_f64, 0.0, 0.0);
        let b = na::Point3::new(1.0, 0.0, 0.0);
        let c = na::Point3::new(0.5, 3.0_f64.sqrt() / 2.0, 0.0);
        assert!(!super::circles_have_triple_intersection(a, 0.3, b, 0.3, c, 0.3));
    }

    #[test]
    fn circles_triple_intersection_ab_overlap_but_not_c() {
        // A and B intersect (ra+rb=1.2>1), but C is far away — neither intersection
        // point falls inside circle C.
        let a = na::Point3::new(0.0_f64, 0.0, 0.0);
        let b = na::Point3::new(1.0, 0.0, 0.0);
        let c = na::Point3::new(10.0, 0.0, 0.0); // far away
        assert!(!super::circles_have_triple_intersection(a, 0.6, b, 0.6, c, 0.6));
    }

    #[test]
    fn check_triangle_corner_inside_object() {
        // Corner c is inside the unit sphere (f = −0.5); must return Some(0.5).
        let sphere = Sphere::new(na::Point3::origin(), 1.0);
        let a = na::Point3::new(2.0_f64, 0.0, 0.0);
        let b = na::Point3::new(0.0, 2.0, 0.0);
        let c = na::Point3::new(0.0, 0.0, 0.5); // f = 0.5 − 1.0 = −0.5
        let result = super::check_triangle(
            &sphere as &dyn super::ImplicitFunction<f64>,
            0.1,
            a,
            sphere.value(&a),
            b,
            sphere.value(&b),
            c,
            sphere.value(&c),
        );
        assert!(result.is_some(), "corner inside object must report unsafe");
        assert!(
            (result.unwrap() - 0.5).abs() < 1e-10,
            "expand distance must equal |f(c)| = 0.5, got {:.6}",
            result.unwrap(),
        );
    }

    #[test]
    fn check_triangle_far_from_surface() {
        // Triangle with all corners far from the unit sphere; large SDF values mean
        // the triple-circle test terminates the recursion immediately.
        let sphere = Sphere::new(na::Point3::origin(), 1.0);
        let a = na::Point3::new(10.0_f64, 0.0, 0.0); // f = 9.0
        let b = na::Point3::new(10.0, 10.0, 0.0);    // f ≈ 13.1
        let c = na::Point3::new(10.0, 0.0, 10.0);    // f ≈ 13.1
        let result = super::check_triangle(
            &sphere as &dyn super::ImplicitFunction<f64>,
            0.1,
            a,
            sphere.value(&a),
            b,
            sphere.value(&b),
            c,
            sphere.value(&c),
        );
        assert!(result.is_none(), "triangle far from surface should be safe");
    }

    #[test]
    fn find_bounds_sphere_at_origin() {
        let sphere = Sphere::new(na::Point3::origin(), 1.0);
        let bbox = super::find_bounds(&sphere as &dyn super::ImplicitFunction<f64>, 0.2);
        assert!(bbox.min.x <= -1.0, "min.x = {:.3}", bbox.min.x);
        assert!(bbox.min.y <= -1.0, "min.y = {:.3}", bbox.min.y);
        assert!(bbox.min.z <= -1.0, "min.z = {:.3}", bbox.min.z);
        assert!(bbox.max.x >= 1.0,  "max.x = {:.3}", bbox.max.x);
        assert!(bbox.max.y >= 1.0,  "max.y = {:.3}", bbox.max.y);
        assert!(bbox.max.z >= 1.0,  "max.z = {:.3}", bbox.max.z);
    }

    #[test]
    fn find_bounds_sphere_offset() {
        // Sphere at (5, 3, −2) radius 1; surface extents [4,6]×[2,4]×[−3,−1].
        let sphere = Sphere::new(na::Point3::new(5.0, 3.0, -2.0), 1.0);
        let bbox = super::find_bounds(&sphere as &dyn super::ImplicitFunction<f64>, 0.2);
        assert!(bbox.min.x <= 4.0,  "min.x = {:.3}", bbox.min.x);
        assert!(bbox.min.y <= 2.0,  "min.y = {:.3}", bbox.min.y);
        assert!(bbox.min.z <= -3.0, "min.z = {:.3}", bbox.min.z);
        assert!(bbox.max.x >= 6.0,  "max.x = {:.3}", bbox.max.x);
        assert!(bbox.max.y >= 4.0,  "max.y = {:.3}", bbox.max.y);
        assert!(bbox.max.z >= -1.0, "max.z = {:.3}", bbox.max.z);
    }

    // -------------------------------------------------------------------------
    // ProgressEvent tests
    // -------------------------------------------------------------------------

    #[test]
    fn progress_fraction_values_and_order() {
        use super::ProgressEvent;
        let events: &[ProgressEvent] = &[
            ProgressEvent::BoundsFound,
            ProgressEvent::SamplingGrid    { done: 0,   total: 100 },
            ProgressEvent::SamplingGrid    { done: 50,  total: 100 },
            ProgressEvent::SamplingGrid    { done: 100, total: 100 },
            ProgressEvent::CompactingGrid  { done: 0,   total: 100 },
            ProgressEvent::CompactingGrid  { done: 100, total: 100 },
            ProgressEvent::GeneratingEdges { done: 0,   total: 100 },
            ProgressEvent::GeneratingEdges { done: 100, total: 100 },
            ProgressEvent::GeneratingVerts { done: 0,   total: 100 },
            ProgressEvent::GeneratingVerts { done: 100, total: 100 },
            ProgressEvent::OctreeLayer     { layer: 0 },
            ProgressEvent::OctreeLayer     { layer: 1 },
            ProgressEvent::OctreeLayer     { layer: 10 },
            ProgressEvent::SolvingQef      { done: 0,   total: 100 },
            ProgressEvent::SolvingQef      { done: 100, total: 100 },
            ProgressEvent::GeneratingQuad  { done: 0,   total: 100 },
            ProgressEvent::GeneratingQuad  { done: 100, total: 100 },
            ProgressEvent::Done            { face_count: 42 },
        ];
        let mut prev = 0.0f32;
        for e in events {
            let f = e.progress_fraction();
            assert!(f >= prev, "{e:?} fraction {f} < previous {prev}");
            assert!(f <= 1.0,  "{e:?} fraction {f} > 1.0");
            prev = f;
        }
        assert_eq!(ProgressEvent::Done { face_count: 0 }.progress_fraction(), 1.0);
    }

    #[test]
    fn progress_monotonic_and_ends_at_one() {
        let sphere = Sphere::new(na::Point3::origin(), 1.0);
        let mut mdc = super::ManifoldDualContouring::new(&sphere, 0.4, 0.0);
        let mut fractions: Vec<f32> = Vec::new();
        mdc.tessellate_with_progress(|e| fractions.push(e.progress_fraction()));
        assert!(!fractions.is_empty(), "no progress events emitted");
        for i in 1..fractions.len() {
            assert!(
                fractions[i] >= fractions[i - 1],
                "non-monotonic: fractions[{}]={} < fractions[{}]={}",
                i, fractions[i], i - 1, fractions[i - 1]
            );
        }
        assert_eq!(fractions.last().copied(), Some(1.0), "last event should be Done (1.0)");
    }
}
